# https://taskfile.dev

version: '3'

tasks:
  build:
    cmds:
      - go build -o runway main.go
    silent: true

  dev:generate:
    cmds:
      - air -build.full_bin "./runway -o ../runway-test generate"
    silent: true

  dev:init:
    cmds:
      - air -build.full_bin "./runway -o ../runway-test init mytest -f"
    silent: true

  template:
    cmds:
      - templ generate --watch
    silent: true

  template:regenerate:
    cmds:
      - find . -type f -name "*_templ.go" | xargs rm {}
      - templ generate
    silent: true

  default:
    deps:
      - dev:generate
