# https://taskfile.dev

version: '3'

tasks:
  build:
    deps:
      - format
    cmds:
      - go build -o runway main.go
    silent: true

  dev:generate:
    deps:
      - format
      - template
      - dev:generate:go
    cmds:
    silent: true

  dev:generate:go:
    cmds:
      - air -build.full_bin "./runway -o ../runway-test generate{{if .CLI_VERBOSE}} -d{{end}}"
    silent: true


  dev:init:
    deps:
      - format
    cmds:
      - air -build.full_bin "./runway -o ../runway-test init mytest -f{{if .CLI_VERBOSE}} -d{{end}}"
    silent: true

  format:
    cmds:
      - go fmt ./...
      - templ fmt .

  template:
    cmds:
      - templ generate --watch
    silent: true

  template:regenerate:
    cmds:
      - find . -type f -name "*_templ.go" | xargs rm {}
      - templ generate
    silent: true

  default:
    deps:
      - dev:generate
