// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package template

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Table() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"bg-white p-4 rounded shadow\"><div class=\"flex justify-between mb-2\"><h2 class=\"text-lg font-semibold\">Items</h2><button class=\"bg-blue-600 text-white px-3 py-1 rounded\" hx-get=\"/items/new\" hx-target=\"#modal\">Add</button></div><table class=\"min-w-full text-sm text-left\"><thead><tr class=\"bg-gray-100\"><th class=\"px-4 py-2\">ID</th><th class=\"px-4 py-2\">Name</th><th class=\"px-4 py-2\">Actions</th></tr></thead> <tbody><tr><td class=\"px-4 py-2\">1</td><td class=\"px-4 py-2\">Example Item</td><td class=\"px-4 py-2 space-x-2\"><button class=\"text-blue-500\" hx-get=\"/items/1/edit\" hx-target=\"#modal\">Edit</button> <button class=\"text-red-500\" hx-delete=\"/items/1\" hx-confirm=\"Are you sure?\" hx-target=\"closest tr\" hx-swap=\"outerHTML\">Delete</button></td></tr></tbody></table></div><div id=\"modal\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
